[package]
name = "FileTP"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
async-stream = "0.3.6"
axum = { version = "0.8.1", features = ["macros", "multipart"] }
bytesize = "1.3.2"
dotenv = "0.15.0"
indicatif = "0.17.11"
maud = { version = "0.27.0", features = ["axum"] }
reqwest = { version = "0.12.12", features = ["multipart", "stream"] }
tokio = { version = "1.43.0", features = ["full"] }
tokio-stream = { version = "0.1.17", features = ["sync"] }
tokio-util = "0.7.13"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
urlencoding = "2.1.3"



[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "client"
path = "src/client.rs"
